In [1]:
import pandas as pd

In [6]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [7]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [9]:
print("Number of rows and columns:",df.shape)
print("Column names:")

Number of rows and columns: (150, 5)
Column names:

In [11]:
print("Database Information")
print("-------------------")
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("\nFirst 5 Records:")
display(df.head())
print("\nLast 5 Records:")
display(df.tail())

Database Information
-------------------
Total Rows: 150
Total Columns: 5

First 5 Records:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Last 5 Records:

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

# Load a CSV Dataset

## objective
To load a CSV dataset using Pandas and display the first and last five recors.

## Tools Used
- Python
- Pandas
- Jupyter Notebook

## Dataset
Iris Dataset

## Conclusiom
The CSV dataset was successfully loaded using Pandas.
The first five and last five records were displayed using head() and tail().